import './globals.css'

export default function RootLayout({
  children,
}: {
    children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header className='flex flex-row justify-between px-12 py-4'>
            <h1>MyApp</h1>
            <nav>
                <ul className='flex gap-4'>
                    <li><a href='#'>Home</a></li>
                    <li><a href='#'>Dashboard</a></li>
                </ul>
            </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
